# Generated by Django 5.2 on 2025-05-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=40)),
                ('employee_salary', models.IntegerField()),
                ('employee_mobile', models.CharField(max_length=15)),
                ('employee_address', models.TextField()),
            ],
        ),
    ]
