# Generated by Django 5.2 on 2025-05-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overallApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_role',
            field=models.CharField(default='Employee', max_length=40),
        ),
    ]
