# Generated by Django 5.2 on 2025-05-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overallApp', '0002_employee_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=40)),
                ('manager_salary', models.IntegerField()),
                ('manager_responsibility', models.TextField()),
            ],
        ),
    ]
